# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spider.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='spider.proto',
  package='spider',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cspider.proto\x12\x06spider\"\x14\n\x04\x44\x61ta\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"\x19\n\x07Results\x12\x0e\n\x06result\x18\x01 \x01(\t22\n\x06Spider\x12(\n\x05Zhihu\x12\x0c.spider.Data\x1a\x0f.spider.Results\"\x00\x62\x06proto3'
)




_DATA = _descriptor.Descriptor(
  name='Data',
  full_name='spider.Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='spider.Data.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=44,
)


_RESULTS = _descriptor.Descriptor(
  name='Results',
  full_name='spider.Results',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='spider.Results.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=71,
)

DESCRIPTOR.message_types_by_name['Data'] = _DATA
DESCRIPTOR.message_types_by_name['Results'] = _RESULTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Data = _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), {
  'DESCRIPTOR' : _DATA,
  '__module__' : 'spider_pb2'
  # @@protoc_insertion_point(class_scope:spider.Data)
  })
_sym_db.RegisterMessage(Data)

Results = _reflection.GeneratedProtocolMessageType('Results', (_message.Message,), {
  'DESCRIPTOR' : _RESULTS,
  '__module__' : 'spider_pb2'
  # @@protoc_insertion_point(class_scope:spider.Results)
  })
_sym_db.RegisterMessage(Results)



_SPIDER = _descriptor.ServiceDescriptor(
  name='Spider',
  full_name='spider.Spider',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=73,
  serialized_end=123,
  methods=[
  _descriptor.MethodDescriptor(
    name='Zhihu',
    full_name='spider.Spider.Zhihu',
    index=0,
    containing_service=None,
    input_type=_DATA,
    output_type=_RESULTS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SPIDER)

DESCRIPTOR.services_by_name['Spider'] = _SPIDER

# @@protoc_insertion_point(module_scope)
