# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sentiment.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sentiment.proto',
  package='sentiment',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fsentiment.proto\x12\tsentiment\"\x19\n\tTextInput\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x19\n\x07Results\x12\x0e\n\x06result\x18\x01 \x01(\t2G\n\tSentiment\x12:\n\x0cGetSentiment\x12\x14.sentiment.TextInput\x1a\x12.sentiment.Results\"\x00\x62\x06proto3'
)




_TEXTINPUT = _descriptor.Descriptor(
  name='TextInput',
  full_name='sentiment.TextInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='sentiment.TextInput.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=55,
)


_RESULTS = _descriptor.Descriptor(
  name='Results',
  full_name='sentiment.Results',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='sentiment.Results.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=82,
)

DESCRIPTOR.message_types_by_name['TextInput'] = _TEXTINPUT
DESCRIPTOR.message_types_by_name['Results'] = _RESULTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TextInput = _reflection.GeneratedProtocolMessageType('TextInput', (_message.Message,), {
  'DESCRIPTOR' : _TEXTINPUT,
  '__module__' : 'sentiment_pb2'
  # @@protoc_insertion_point(class_scope:sentiment.TextInput)
  })
_sym_db.RegisterMessage(TextInput)

Results = _reflection.GeneratedProtocolMessageType('Results', (_message.Message,), {
  'DESCRIPTOR' : _RESULTS,
  '__module__' : 'sentiment_pb2'
  # @@protoc_insertion_point(class_scope:sentiment.Results)
  })
_sym_db.RegisterMessage(Results)



_SENTIMENT = _descriptor.ServiceDescriptor(
  name='Sentiment',
  full_name='sentiment.Sentiment',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=84,
  serialized_end=155,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetSentiment',
    full_name='sentiment.Sentiment.GetSentiment',
    index=0,
    containing_service=None,
    input_type=_TEXTINPUT,
    output_type=_RESULTS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SENTIMENT)

DESCRIPTOR.services_by_name['Sentiment'] = _SENTIMENT

# @@protoc_insertion_point(module_scope)
